# Generated by Django 4.1.7 on 2023-03-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_added',
        ),
    ]
