# Generated by Django 4.1.7 on 2023-03-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_added',
        ),
    ]
