# Generated by Django 4.1.7 on 2023-03-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_small_description_alter_post_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='small_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
