# Generated by Django 4.1.7 on 2023-03-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_remove_comment_date_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
