# Generated by Django 4.1.7 on 2023-03-30 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0025_blogcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='PostComment',
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-date_posted']},
        ),
    ]
