# Generated by Django 4.1.7 on 2023-04-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
